language: node_js
node_js:
- node
deploy:
  api_key:
    secure: cSjlHLNH+h16yeO3a+ZZgvSDiOU4kw6e4xhh2757BdF2qy57eyoV0y0N6ovAJdJoCiMbfFScAM/v2qtD9WN3uv72nzsYY5VmEz0JibsYGx6NUN2uK+elbAuekRgVTh/z+vXFMbovef/qPbHCZvJPV+Vd/1VoqNoEkvRgdcSKH9d8dq0qqBezdbPml71+tD1Y1/VS/3I2Nb0GEHidpMCMvIbMTDg9c8JZ3Y4lm4mgtfv+fsefPmIAUeVZYlDK392uClhvDV/Ytlyk5nkiFUik4F7hi+4WVr7+icEMJFA/3yDIrpLt0L5nrAm4l+BjAZwMiiF4qkL9VzjhawoonrHwx+Bhs9BcXS9VDPksDa8Z9RSv3AfDi/v3EEcaLVY/mTDKuz2wz+xOeAnNjQU5YVVbWqHbF0Uvdh3SnyHMjAeViK86t9JDjdKtGf/prrbq6MqF0VbbfqIQKWqrGvpaxJyScqF89POVzbs0qRjixLFyGxngb98f07bzBWO35aheIiVZN9yxmAe3x5nw/Tx6/rbKb6i3ISQz86dMoxNg5zV6L5G1bPB46QSGlFW+cagFivyCYYGzbE6RddlojyyYNFAByP8BCTQHM0DwXKPWO6RnW6R7gTAkikUmXiX+dwrNbdkmV5Jg7e4bYxrSrJGT5cEPD8h9jQq3Y+d/i9TYCBxIgSI=
