language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: CRiI4YOoz2VENm36MgDcKI61KzrRsxCcqq4gXpX9ryN06+y6+G/D+thEgfuBwbCWOjOc2e6oAKjfDjbMm7j3Be/iZsbwLZU/uuGModPgBOH6dnsadWeLMiD2GovHd2Y5LQhcCQqLTFFZiDAJZLR/Xx3+YBMwiJ/fSnj59U7JvXd8FQOAPtfwADNjzwxGT2PmgqO15MdJ9/lnJXrYnhGCoUBGEFXARoUW8u6FturSYi7Ersz5fCwrY2ga5JkEXvugNOlWQLimGm2s2RmHTNSJ5KP7BvfStRpTZpeK5OJstkge1H46jMPKUvbTeknpbB4Vqh7SkSEtKufZN/CNHw6NM1MBPVnZEc6qCsjRdrB5OFb0Ozw0MLDI8CnssEWqcJlHwP8/pCuUh9HzfMJBwsn7ImRcMUHDOJiP9CPP5rxp9CCvuYQipMgztLsOTlVgXBxZkNwnQ28K2g2k6srXyjuCfo1FtPCl9CvnB4abTqlwObCWVXpoAIKdUTvlEhgDuubPWMZknWUkUeal5qD1isu3gRQWqkdgCMDvJEYcnD9feFDf/VtL9VMW8ebTIa7JMLty0vOSkeR2dHvMUrFf6Rh1jENt5lyziRZSFKptog7rP8aZOm8nAvF08lWdrqpwEit7dW9gCb/xsQbD5455gekoPtlQVAOpRuvSfRYHd0R1OyU=
  app: dumball-story
