language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: Fu9w/CpPEro5db8oLV+Mtend6YCC2HuOZb2lGKfmglj0VYAWMMIiGSm0KbPmMM5bkCTeElLy2LJpzJptjASQBGdyot++i4oOPQN6/JNRZ0AVd8fsNVJ6kTxxV6CsYMdlHa3+It9m15FAjdiSGEqx82QBS9/xHUBffgrj/DKdv3KrePwPcOcz+RuOmtToNbhjrzeshb1OZ464K6LS7t74TsGsfa8zBJHULx2LA+Em/qMXX5lMWJn0x9dl/083ZWipAyDu7KFUenpOo0+k5IxqvP66NphFfsN+uCm0/BEisIAtBAbgoIBW4GMSNClQZ6ph5+FTxhnNAZrb7EigY8vaaWhcafXLj+HufvSB4Hs7fxlaXxPm0lVQaSIrvcZ+LdesqyLzlT+zTv5ef1i/Tc21WGZgABaeLmRAaq0Z1BUw6R2A//rTCYL/i9Y30ARUURcz0z8pxy+xo7oYVNmjHww7KEmWV1+QBT2xq+8Lne9PkzCUDedmiPyp/Z4NQ/hRwGhCX/atvvs2na8E+fC9Q7BWUJQkyAHdRgAVD58BOSoW9v+YYfAQkjGWpv4lLfQNAhlS6kzf9kFUoIACK/3wFgVtu7PWvmI6rQN97CV9GQTeppIYLpMbRHkl8vSEgRnROfaSgJyciRIauPPNBoJU9WTQzLJmQrGj71bk3Sko/hMYl+8=
  app: dumball-story
    on:
    repo: revilo1882/dumball_2018
